# fly.toml app configuration file generated for expense-tracker-holy-breeze-5074 on 2025-04-23T20:16:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'expense-tracker-holy-breeze-5074'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
